- name: Install HAProxy
  apt:
    name: haproxy

# Use 'dns_record' role to add CNAME records for each server in the 'haproxy_servers' group.
- name: Add HAProxy A Records
  include_role:
    name: dns_record
    tasks_from: add_dns_records
  vars:
    record: "lb-{{server_index + 1}}"
    value: "{{ item }}"
    type: "CNAME"
  loop: "{{ groups['haproxy_servers'] }}"
  loop_control:
    index_var: server_index

- name: Template haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Start HAProxy
  service:
    name: haproxy
    state: started
    enabled: true

- name: Install HAProxy Exporter
  apt:
    name: prometheus-haproxy-exporter

- name: Enable and Start HAProxy Exporter
  service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true

- name: Configure HAProxy Exporter
  template:
    dest: /etc/default/prometheus-haproxy-exporter
    src: prometheus-haproxy-exporter
  notify: Restart HAProxy Exporter
