# Not /temp to avoid .deb file disappearing
- name: Create InfluxDB Download Directory
  file:
    path: /opt/influxdb
    state: directory

- name: Download InfluxDB
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
    dest: /opt/influxdb/influxdb_1.8.10_amd64.deb

- name: Install InfluxDB
  apt:
   deb: "/opt/influxdb/influxdb_1.8.10_amd64.deb"

- name: Template influxdb.conf
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    mode: 0644
  notify: Restart InfluxDB

- name: Enable and Start InfluxDB
  service:
    name: influxdb
    state: started
    enabled: true

- name: Create Directory for APT Key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Get Telegraf Repository Key
  get_url:
    url: https://repos.influxdata.com/influxdata-archive.key
    dest: /etc/apt/keyrings/telegraf.asc
    mode: 0644

- name: Add Telegraf Repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/telegraf.asc] https://repos.influxdata.com/debian stable main"
    state: present
    update_cache: true

- name: Install Telegraf 1.28.2
  apt:
    name: telegraf=1.28.2-1
    state: present

- name: Template telegraf.conf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: 0644
  notify: Restart Telegraf

- name: Enable and Start Telegraf
  service:
    name: telegraf
    state: started
    enabled: true

- name: Download InfluxDB exporter
  get_url:
    mode: 0770
    owner: prometheus
    group: prometheus
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/influx_stats_exporter

- name: Create influxdb-stats-exporter Service
  template:
    src: influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service

- name: Restart systemctl daemon
  systemd:
   daemon_reload: true

- name: Start InfluxDB Stats Exporter
  service:
    name: prometheus-influxdb-stats-exporter.service
    state: started
    enabled: true

- name: Create Restore Directory 
  file:
    path: /home/backup/restore/influxdb
    state: directory
    owner: backup
    group: backup
    mode: 0770

- name: Create Backup Directory
  file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    group: backup
    mode: 0770

- name: Create InfluxDB Backup Cron
  template:
    src: cron-influxdb-backup.j2
    dest: /etc/cron.d/influxdb-backup

# Use 'dns_record' role to add CNAME record for server in the 'influxdb_servers' group.
- name: Add InfluxDB A Record
  include_role:
    name: dns_record
    tasks_from: add_dns_records
  vars:
    record: "influxdb"
    value: "{{ groups['influxdb_servers'][0] }}"
    type: "CNAME"