- name: Create InfluxDB Download Directory
  ansible.builtin.file:
    path: /opt/influxdb
    state: directory

- name: Download InfluxDB
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
    dest: /opt/influxdb/influxdb_1.8.10_amd64.deb

- name: Install influxdb
  ansible.builtin.apt:
   deb: "/opt/influxdb/influxdb_1.8.10_amd64.deb"

- name: Template influxdb.conf
  ansible.builtin.template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    mode: '0644'
  notify: Restart InfluxDB

- name: Enable and Start InfluxDB
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: true

- name: Create Telegraf Download Directory
  ansible.builtin.file:
    path: /opt/telegraf
    state: directory

- name: Download Telegraf
  ansible.builtin.get_url:
    url: "https://dl.influxdata.com/telegraf/releases/telegraf_1.28.2-1_amd64.deb"
    dest: "/opt/telegraf/telegraf_1.28.2-1_amd64.deb"

- name: Install Telegraf
  ansible.builtin.apt:
    deb: "/opt/telegraf/telegraf_1.28.2-1_amd64.deb"

- name: Create Telegraf directory
  ansible.builtin.file:
    path: /etc/telegraf
    state: directory

- name: Template telegraf.conf
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: '0644'
  notify: Restart Telegraf

- name: Enable and Start Telegraf
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: true

- name: Download InfluxDB exporter
  get_url:
    mode: 0770
    owner: prometheus
    group: prometheus
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/influx_stats_exporter

- name: Create influxdb-stats-exporter Service
  ansible.builtin.template:
    src: influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service

- name: Restart systemctl daemon
  systemd:
   daemon_reload: true

- name: Start InfluxDB Stats Exporter
  service:
    name: prometheus-influxdb-stats-exporter.service
    state: started
    enabled: true