- name: Install Grafana via Docker
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
    restart_policy: "unless-stopped"

- name: Create Provisioning Directories
  ansible.builtin.file:
    path: /opt/grafana/provisioning/{{ item }}
    state: directory
  loop:
    - dashboards
    - datasources

- name: Template grafana.ini
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: Restart Grafana
  no_log: true

- name: Template dashboards.yaml
  template:
    src: dashboards.yaml
    dest: /opt/grafana/provisioning/dashboards/dashboards.yaml
  notify: Restart Grafana

- name: Template datasources.yaml
  template:
    src: datasources.yaml
    dest: /opt/grafana/provisioning/datasources/datasources.yaml
  notify: Restart Grafana

- name: Copy Dashboards
  copy:
    src: "{{ item }}"
    dest: /opt/grafana/provisioning/dashboards/{{ item }}
  loop:
    - main.json
    - mysql.json
    - syslog.json
  notify: Restart Grafana

- name: Add Grafana A Record
  include_role:
    name: dns_record
    tasks_from: add_dns_records
  vars:
    record: "grafana"
    value: "{{ groups['grafana_servers'][0] }}"
    type: "CNAME"