---
- name: Install uWSGI
  ansible.builtin.apt:
    name: uwsgi
    state: present

- name: Install Dependencies
  ansible.builtin.apt:
    name: uwsgi-plugin-python3
    state: present      

- name: Template uWSGI config
  ansible.builtin.template:
    src: ../templates/agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  no_log: true
  notify: Restart uWSGI

- name: Enable and start uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true
