---
  - name: Initial setup
    hosts: all
    roles:
      - init
    tasks:
      - name: Update APT cache
        ansible.builtin.apt:
          cache_valid_time: 86400

  - name: Web Server
    hosts: web_servers
    roles:
      - nginx 