{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", job=\"linux\"}[10m])) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{job=\"linux\"}[10m]) + avg_over_time(node_memory_Cached_bytes{job=\"linux\"}[10m]) + avg_over_time(node_memory_Buffers_bytes{job=\"linux\"}[10m])) / avg_over_time(node_memory_MemTotal_bytes{job=\"linux\"}[10m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bind9 Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HAProxy 1 Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"YukobaTTU-1:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived 1 Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_up{instance=\"YukobaTTU-1:9165\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived 1 VRRP State ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"YukobaTTU-1:9165\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy 2 Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"YukobaTTU-2:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived 2 Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_up{instance=\"YukobaTTU-2:9165\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived 2 VRRP State ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"YukobaTTU-2:9165\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "idelta(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy 1 Container Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"YukobaTTU-1:9101\"}",
     "legendFormat": "{{ instance }}, {{ server }}"
    }
   ]
  },
  {
   "title": "SELECT Queries ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "idelta(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy 2 Container Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"YukobaTTU-2:9101\"}",
     "legendFormat": "{{ instance }}, {{ server }}"
    }
   ]
  },
  {
   "title": "DNS Queries ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "idelta(bind_resolver_queries_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "idelta(influxdb_write_write_ok[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pinger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "taltech.ee",
     "query": "SELECT * FROM \"rtt\" WHERE \"dst\" = 'taltech.ee'"
    },
    {
     "alias": "google.com",
     "query": "SELECT * FROM \"rtt\" WHERE \"dst\" = 'google.com'"
    },
    {
     "alias": "8.8.8.8",
     "query": "SELECT * FROM \"rtt\" WHERE \"dst\" = '8.8.8.8'"
    }
   ]
  }
 ]
}