- name: Restart Bind9
  service:
    name: bind9
    state: restarted

- name: RNDC Reload Bind9
  command: rndc reload
  changed_when: true

- name: Restart Bind Exporter
  service:
    name: prometheus-bind-exporter
    state: restarted