- name: Create User
  user:
    user: agama
    state: present

- name: Create Directory
  file:
    owner: agama
    state: directory
    path: /opt/agama

- name: Install Dependencies
  apt:
    name: 
      - python3-flask-sqlalchemy
      - python3-pymysql    
    state: present

- name: Install Agama
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama
