apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://{{groups['web_servers'][0]}}/prometheus
    editable: false

  - name: InfluxDB-pinger
    type: influxdb
    access: proxy
    url: http://{{groups['pinger_servers'][0]}}:8086
    editable: false
    jsonData:
      dbName: pingerdb
      httpMode: GET

  - name: InfluxDB-telegraf
    type: influxdb
    access: proxy
    url: http://{{groups['influxdb_servers'][0]}}:8086
    jsonData:
      dbName: telegraf
      httpMode: POST