- name: Install fping
  apt:
    name: fping
    state: present

- name: Create pinger User
  user:
    name: pinger

- name: Copy pinger.sh
  copy:
    src: pinger.sh
    owner: pinger
    group: pinger
    mode: 0770
    dest: /usr/local/bin/pinger

- name: Create systemd Service Unit File
  template:
    src: pinger.service.j2
    dest: /etc/systemd/system/pinger.service

- name: Reload systemd Configuration
  systemd:
    daemon_reload: yes

- name: Create /etc/pinger directory
  file:
    path: /etc/pinger
    state: directory

- name: Copy pinger.conf
  template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf

- name: Enable and Start pinger
  service:
    name: pinger.service
    state: started
    enabled: yes