- name: Install Prometheus
  apt:
    name: prometheus
    state: present

- name: Enable and Start Prometheus
  service:
    name: prometheus
    state: started
    enabled: true

- name: Template Config
  template:
    dest: /etc/prometheus/prometheus.yml
    src: config.yaml.j2
    mode: '0644'
  notify: Restart Prometheus

- name: Template Metrics
  template:
    src: metrics.yaml.j2
    dest: /etc/default/prometheus
    mode: '0755'
  notify: Restart Prometheus