- name: Install Prometheus
  apt:
    name: prometheus


# add prefix web.external-url... to get a correct redirection url from http://.../prometheus
- name: Edit Prometheus Service
  template:
    src: prometheus
    dest: /etc/default/prometheus
  notify: Restart Prometheus

- name: Template prometheus.yml
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Add Prometheus A Record
  include_role:
    name: dns_record
    tasks_from: add_dns_records
  vars:
    record: "prometheus"
    value: "{{ groups['prometheus_servers'][0] }}"
    type: "CNAME"