- name: Install Bind9
  apt:
    name: bind9

- name: Template Bind9 Config
  template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
  loop:
    - options
    - local
  notify: Restart Bind9
  no_log: true

- name: Template Master Zone Config
  template:
    src: "{{ item }}.j2"
    dest: /var/cache/bind/db.{{ item }}
    force: false
  notify: Restart Bind9
  loop: 
  - "{{ domain_name }}"
  - "{{ reverse_domain_name }}"
  when: inventory_hostname in groups['bind_masters']

- name: Install Bind Exporter
  apt:
    name: prometheus-bind-exporter

- name: Enable and Start Bind9 and Exporter
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - bind9
    - prometheus-bind-exporter

# Run handlers before adding DNS records
- name: Run Handlers
  meta: flush_handlers

# Use 'dns_record' role to add A records for backup IP and google IP on each server in the 'agama_servers' group only if the host is in the 'bind_masters' group.
# map('dict2items'): Converts the dictionary into a list of key-value pairs.
# flatten: Flattens the list of dictionaries into a single list.
# Ex.
# - host1
# - 192.168.1.1
# - host2
# - 192.168.1.2
- name: Add A Records
  include_role:
    name: dns_record
    tasks_from: add_dns_records
  vars:
    record: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "A"
  loop: "{{ a_records | map('dict2items') | flatten }}"
  when: inventory_hostname in groups['bind_masters']

# Use 'dns_record' role to add NS records for each server in the 'bind_masters' group.
- name: Add NS Records
  include_role:
    name: dns_record
    tasks_from: add_dns_records
  vars:
    record: "ns-{{server_index + 1}}"
    value: "{{ item }}"
    type: "CNAME"
  loop: "{{ groups['bind_servers'] }}"
  loop_control:
    index_var: server_index
  when: inventory_hostname in groups['bind_masters']