#- name: Ansible ping module
#  ansible.builtin.ping:

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Update resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: '0644'

- name: Shutdown systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Install Prometheus Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Install CA Certificates
  ansible.builtin.apt:
    name: ca-certificates>=20230311ubuntu0.20.04.1

- name: Install rsyslog
  ansible.builtin.apt:
    name: rsyslog
    state: present

- name: Configure rsyslog to use only UDP
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^module(load="imudp")'
    line: 'module(load="imudp")'

- name: Send Logs to Telegraf
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    line: '*.* @localhost:6514'
  notify: Restart rsyslog