- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Download Certificates
  apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    update_cache: true

- name: Install Prometheus Node Exporter
  apt:
    name: prometheus-node-exporter

- name: Copy rsyslog Config
  copy:
    src: rsyslog-tel.conf
    dest: /etc/rsyslog.d/tel.conf
  notify: Restart rsyslog

- name: Create Backup User
  user:
    name: backup
    home: /home/backup
    generate_ssh_key: true
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: Template known_hosts
  template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: 0600

- name: Create Restore Directory 
  file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: 0777

- name: Install Duplicity
  apt:
    name: duplicity

- name: Install dnspython
  apt:
    name: python3-dnspython